### ISSUE TITLE
HTML files should not be cached in the browser

### ISSUE THREAD

**Issue by kylekirkby** [linaro-its/github-action-scripts#3]
Cloudfront **should** be in control of the HTML caching. Current the max-age is set to 86400 causing browsers to cache the HTML. 

```
 max-age=0 in combination with must-revalidate ensure browsers never cache the static pages.
```

See the following for an example of how the caching should be set for static HTML files:
https://github.com/serverless-nextjs/serverless-next.js#static-pages-caching

This file should be modifed to set the correct headers for `.html` files:
https://github.com/linaro-its/github-action-scripts/blob/main/upload-to-s3-root.sh#L6

**Comment by pcolmer** [comment]
> max-age=0 in combination with must-revalidate ensure browsers never cache the static pages.

I'm not sure I'm happy with that. Browsers are designed to cache content. They should be querying upstream to make sure that what is in the cache is still appropriate compared with what is upstream.

If the problem is that a browser is using a cached copy when Cloudfront has a newer copy then let's investigate that as that shouldn't be the case.

**Comment by kylekirkby** [comment]
@pcolmer,

> They should be querying upstream to make sure that what is in the cache is still appropriate compared with what is upstream.

This is essentially what this would be doing. The HTML files would stay in the Cloudfront edge cache. When a page is requested, the best case would be only a single tiny HTML file is transferred from the nearest cf edge server.

Do you have another suggestion on how we can be "querying upstream to make sure that what is in the cache is still appropriate"? All examples of hosting static websites I've looked at, say to never cache the HTML in the browser to ensure that the clients always get the latest page.

HTML changes most often. CSS/Javascript/Images are changed a lot less, so this would **only** be applied to HTML files.

**Comment by pcolmer** [comment]
When I say "querying upstream", the browser would be performing a HEAD query to determine when the content was last modified.

As we discovered when we were trying to get fess working properly, when the content is uploaded to S3, everything gets "today's" date stamped on it. So, a browser should always end up fetching fresh content because it will seem newer than what the browser has.

> Do you know of any reputable guides/documentation for hosting static sites that suggest caching HTML in the browser?

Nope 😁

**Comment by pcolmer** [comment]
Agreed to use `no-cache` (per https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) to force browsers to check HTML pages each time. It is a small data transfer and equivalent to a "soft" refresh on every page visit.

**Comment by pcolmer** [comment]
I've updated the script that syncs the files to S3 and forced a resync of the entire linaro.org website. It will be necessary to remove the s3 cache on the build server for each of the websites and then force a push for each of the websites in order to update the cache control headers.

Even that isn't the end of the story. If a user's browser currently has a page cached, it will be cached with the old cache headers, so they *still* need to refresh the page once to get the new cache headers. After that, the browser will quickly check each page before reusing it from its own cache.

**Comment by kylekirkby** [comment]
@pcolmer - thanks for this update!
